### ISSUE TITLE
[ISSUE][EMPLEADOS] Not actualitation on user list scroll

### ISSUE THREAD

**Issue by I-Encinas** [RmichelV/Hostal_Nomada#11]
In the user scroll should appear a complete user list, but just appear logged user option
1. Go to CREATE NEW EMPLOYEE
2. Select user option
![image](https://github.com/user-attachments/assets/de731ffb-0570-4555-9991-04c8f5093f5e)

**Comment by RmichelV** [comment]
Arreglado
