### ISSUE TITLE
[BUG][MODULO DE RESTAURANTE] NO INGRESA A LA PÁGINA CORRESPONDIENTE

### ISSUE THREAD

**Issue by estebanc7856** [RmichelV/Hostal_Nomada#23]
Cuando se apreta el botón del navbar restaurante no redirige a la pagina correspondiente, lleva directamente a reservación de habitaciones 
![image](https://github.com/user-attachments/assets/08c2e65a-2e72-4cb6-87f8-277dc2526819)
![image](https://github.com/user-attachments/assets/8096c8d8-f6b5-4485-8406-460be5212c85)

**Comment by RmichelV** [comment]
El bug ha sido solucionado, ya redirige a restaurante
