### ISSUE TITLE
[BUG][MODULO DE RESERVA] NO SELECCIONA LA HABITACIÓN

### ISSUE THREAD

**Issue by estebanc7856** [RmichelV/Hostal_Nomada#24]
Cuando seleccionas la habitación no te muestra cual estas seleccionando pero te muestra el precio, entonces cuando haces la reserva te salta un error diciéndote que tienes que elegir un tipo de habitación 
![image](https://github.com/user-attachments/assets/e6d6f810-4123-4f1b-afd8-5f34bcd1b179)
![image](https://github.com/user-attachments/assets/6c5903a7-f21f-4cef-8ec1-56f3bb1a962b)

**Comment by RmichelV** [comment]
Error solucionado, ya selecciona la habitación
