### ISSUE TITLE
[DEFECTO][PÁGINA PRINCIPAL]PÁGINA NO RESPONSIVE

### ISSUE THREAD

**Issue by Yosimaciel22** [RmichelV/Hostal_Nomada#28]
Cuando el tamaño de la ventana cambia, el tamaño de la página no se adecua a la pantalla.
![image](https://github.com/user-attachments/assets/05910cb4-7d00-4bde-ad6d-e543ab2b25dd)

**Comment by RmichelV** [comment]
Ahora los titulos de las habitaciones ya son responsive
<img width="809" alt="image" src="https://github.com/user-attachments/assets/104baba3-fa52-45b4-9dd9-44e06c51bf7f">
