### ISSUE TITLE
[ISSUE][REGISTRO, CLIENTE]Permite la creación de números telefònicos no existentes 

### ISSUE THREAD

**Issue by Yosimaciel22** [RmichelV/Hostal_Nomada#29]
Al momento de ingresar el numero telefónico, permite números como "000000000", la cual es inexistente.

![image](https://github.com/user-attachments/assets/3b1c4786-93c1-4788-93d1-bf3c5aaea55d)

**Comment by RmichelV** [comment]
el issue ha sido resuelto: 
<img width="665" alt="image" src="https://github.com/user-attachments/assets/d6f3cd25-e0dd-4831-b252-b49a2ce5b688">

**Comment by RmichelV** [comment]
el issue ha sido resuelto: 
<img width="665" alt="image" src="https://github.com/user-attachments/assets/d6f3cd25-e0dd-4831-b252-b49a2ce5b688">
