### ISSUE TITLE
[DEFECTO][VERIFICACIÓN DE EMAIL]NO EXISTE UN BOTON DE REGRESO A LA PAGINA ANTERIOR

### ISSUE THREAD

**Issue by Yosimaciel22** [RmichelV/Hostal_Nomada#30]
Al momento de verificar el email del usuario en proceso de registro, no existe un botón de regreso a la página anterior
![image](https://github.com/user-attachments/assets/f838730d-d81f-4b76-892e-677af99b84f1)

**Comment by RmichelV** [comment]
Ya se agrego el menu para poder moverse a diferentes pestañas
