### ISSUE TITLE
[DEFECTO][INICIO DE SESIÓN]NO EXISTE UN BOTON DE REGRESO A LA PAGINA ANTERIOR

### ISSUE THREAD

**Issue by Yosimaciel22** [RmichelV/Hostal_Nomada#31]
Al momento de iniciar sesión, en caso de que el usuario decida realizar otra acción, no tiene acceso a retroceder a la página anterior mediante un botón de regreso. 
![image](https://github.com/user-attachments/assets/32d34bc0-4d9c-4542-b95d-8a2c2a297286)

**Comment by RmichelV** [comment]
Ahora el menu de navegacion esta visible para poder moverse a otras pestañas
