### ISSUE TITLE
[ISSUE][RECUPERACION DE CONTRASEÑA]VALIDACIÓN EN INGLES

### ISSUE THREAD

**Issue by Yosimaciel22** [RmichelV/Hostal_Nomada#32]
El idioma de validación, que en este caso es "correo no encontrado", esta en ingles, idioma no determinado en el sistema.
![image](https://github.com/user-attachments/assets/ec1dd2b7-38e2-499d-beff-4d57245580f9)

**Comment by RmichelV** [comment]
el mensaje aparece en español ahora: 
![image](https://github.com/user-attachments/assets/76ddd584-2cb4-4519-b758-70b8e000a5b5)
