### ISSUE TITLE
[DEFECTO][RECUPERQACIÓN DE CONTRASEÑA]NO EXISTE UN BOTON DE REGRESO A LA PÁGINA ANTERIOR

### ISSUE THREAD

**Issue by Yosimaciel22** [RmichelV/Hostal_Nomada#33]
EL usuario después de enviar el correo para la recuperación correspondiente de su cuenta, no tiene el acceso al regreso a la página anterior
![image](https://github.com/user-attachments/assets/4d73724f-75cf-46eb-b57b-74148eaf5d2f)

**Comment by RmichelV** [comment]
Ya hay botones para moverse a las diferentes paginas
