### ISSUE TITLE
[DEFECTO][LISTA DE EMPLEADOS]No existe la opcion de editar, eliminar

### ISSUE THREAD

**Issue by Yosimaciel22** [RmichelV/Hostal_Nomada#35]
No puede rellenarse la lista ya que no existe la opcion de editar o eliminar si es pertinente
![image](https://github.com/user-attachments/assets/eb466b00-2026-418f-9f1a-975326d91d7b)

**Comment by RmichelV** [comment]
Se debe agregar primeramente un empleado para poder editar su información
