### ISSUE TITLE
[ERROR][AGREGAR EMPLEADO]

### ISSUE THREAD

**Issue by Yosimaciel22** [RmichelV/Hostal_Nomada#36]
Al momento de agregar un nuevo empleado, al elegir usuario solo aparece el usuario logeado y no lo usuarios registrados
![image](https://github.com/user-attachments/assets/bc667a62-75ac-485d-8a94-3bf01479d958)

**Comment by RmichelV** [comment]
No es error, solo apareceran usuarios con algun rol distinto al de cliente
