### ISSUE TITLE
[ERROR][LISTA DE RESERVACIONES, ADMINISTRADOR]

### ISSUE THREAD

**Issue by Yosimaciel22** [RmichelV/Hostal_Nomada#38]
Al intentar agregar una reservacion, no se logra realizar por no marcarse el tipo de habitacion
![image](https://github.com/user-attachments/assets/ad1b88ae-4152-4d28-a191-2eaf8d9f07f9)

**Comment by RmichelV** [comment]
Ya se puede seleccionar el tipo de habitacion
